baseURL                   = "https://example.com"
builddrafts                = false
languageCode               = "zn-Hans"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

theme                      = "AllinOne"
title                      = "Gaurav Mishra"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "About"
    weight                 = -120
    identifier             = "about"
    url                    = "about/"  

  [[menu.main]]
    name                   = "Articles"
    weight                 = -110
    identifier             = "articles"
    url                    = "articles/" 
 
 [[menu.main]]
    name                   = "Projects"
    weight                 = -110
    identifier             = "projects"
    url                    = "projects/"



  [[menu.main]]
    name                   = "Aside1: Music"
    weight                 = -100
    identifier             = "Music"
    url                    = "aside1/"  

 

[params]
  faviconfile              = "img/avatar.png"               # from static/
  avatar                   = "img/gaurav_dp2.jpeg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Gaurav Mishra"
  description              = ["Machine Learning Enthusiast", "Deep Learning", "ECE Graduate"]           # appears in the site header when set to a non-empty string
  welcome_head             = "Hi visitor"
  welcome_word             = "~ ssup ~"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "in.gaurav.mishra@gmail.com"
  github                   = "https://github.com/mishragauravgm"
  linkedin                 = "https://www.linkedin.com/in/gauravmishra1234/"
  #facebook                 = "//facebook.com/you"
  #googleplus               = "//google.com/you"
  instagram                = "//instagram.com/mishraa_gaurav"
  googlescholar            = "//googleshilar.com"
  include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  googleAnalytics          = "your-google-analytic-id"
    
    